# Generated by Django 5.2.7 on 2025-10-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
