# Generated by Django 5.2.7 on 2025-10-26 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0002_donacion_direccion'),
        ('solicitudes', '0002_solicitud_detalle_solicitud_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='donacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='donaciones.donacion'),
        ),
    ]
