# Generated by Django 5.2.7 on 2025-10-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.TextField(max_length=150, null=True, unique=True),
        ),
    ]
