"""
Django settings for SIGDC project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Construir rutas dentro del proyecto así: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Ajustes rápidos para desarrollo - no aptos para producción
# Ver https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Load secrets / runtime flags from environment to avoid leaking production values
# In production set DJANGO_SECRET_KEY and DJANGO_DEBUG (or use a secrets manager)
SECURE_HSTS_SECONDS = 31536000
DEFAULT_INSECURE_SECRET = 'django-insecure-r$=-6n*!6ug5h8t9n3x-(ryq*%fn+%c$y4nap3qokj^ix09s_s'
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', DEFAULT_INSECURE_SECRET)

# Aplicación de lista de verificación de seguridad para producción:
#    export DJANGO_DEBUG=False
#    export DJANGO_SECRET_KEY='<django-insecure-r$=-6n*!6ug5h8t9n3x-(ryq*%fn+%c$y4nap3qokj^ix09s_s>'
#    export DJANGO_SECURE_HSTS_SECONDS=31536000
#    export DJANGO_SECURE_SSL_REDIRECT=True
#    export DJANGO_SESSION_COOKIE_SECURE=True
#    export DJANGO_CSRF_COOKIE_SECURE=True
#    export DJANGO_SECURE_HSTS_PRELOAD=True

# DEBUG should be explicitly controlled by environment for deploys. Default to True
# for local development but you should set DJANGO_DEBUG=False in production.
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Definición de la aplicación

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'donaciones',
    'usuarios.apps.UsuariosConfig',
    'solicitudes',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

ROOT_URLCONF = 'SIGDC.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR  / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SIGDC.wsgi.application'


# Base de datos
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Validación de contraseñas
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internacionalización
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Archivos estáticos (CSS, JavaScript, Imágenes)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# URLs de login/redirección para las vistas protegidas
LOGIN_URL = '/usuarios/login/'
LOGIN_REDIRECT_URL = '/usuarios/menu/'

# Tipo de campo primary key por defecto
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración CORS (django-cors-headers)
# Permitir que cookies/credenciales se envíen en peticiones cross-origin cuando esté configurado
CORS_ALLOW_CREDENTIALS = True

# NOTA: Ajusta los orígenes permitidos para tu despliegue. Para desarrollo puedes
# permitir entradas localhost abajo. Evita CORS_ALLOW_ALL_ORIGINS = True en
# producción salvo que entiendas las implicaciones de seguridad.
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]

# Cabeceras Anti-XSS / protección contra clickjacking
# Activar el filtro XSS del navegador y establecer opciones de frame en DENY
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Política de Host / Referrer y manejo opcional de proxy
# Restringir hosts permitidos (valores por defecto para desarrollo). Ajustar para producción.
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
USE_X_FORWARDED_HOST = True

# Security / hardening options. Provide values via environment variables in
# production (or via a secrets manager). Many of these defaults are intentionally
# permissive for local development but should be tightened for deployments.

# HSTS: number of seconds clients should respect Strict-Transport-Security.
# Set DJANGO_SECURE_HSTS_SECONDS to a positive integer (e.g. 31536000 for 1yr)
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '0'))
if SECURE_HSTS_SECONDS > 0:
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True') == 'True'
    SECURE_HSTS_PRELOAD = os.getenv('DJANGO_SECURE_HSTS_PRELOAD', 'False') == 'True'

# Force HTTPS in production behind a reverse proxy/load-balancer if needed.
SECURE_SSL_REDIRECT = os.getenv('DJANGO_SECURE_SSL_REDIRECT', 'False') == 'True'

# Cookies should be secure (only sent over HTTPS) in production.
SESSION_COOKIE_SECURE = os.getenv('DJANGO_SESSION_COOKIE_SECURE', str(not DEBUG)) == 'True'
CSRF_COOKIE_SECURE = os.getenv('DJANGO_CSRF_COOKIE_SECURE', str(not DEBUG)) == 'True'

# Re-enforce the existing headers if needed (kept enabled by default)
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Validate critical production requirements when DEBUG is disabled.
if not DEBUG:
    # Secret key must be properly set in production and must not be the default
    if not SECRET_KEY or SECRET_KEY.startswith('django-insecure') or len(SECRET_KEY) < 50 or len(set(SECRET_KEY)) < 5:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set to a long, random value for production.'
        )

