name: CI/CD Deploy SIGDC

on:
  push:
    branches:
      - kikin3

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Copiar proyecto a la carpeta real del servidor (sin borrar env)
        run: |
          sudo rsync -av --delete \
            --exclude env \
            /home/kikin/actions-runner/_work/SIGDC/SIGDC/ \
            /home/kikin/sites/SIGDC/

      - name: Activar entorno virtual
        run: |
          source /home/kikin/sites/SIGDC/env/bin/activate

      - name: Instalar dependencias
        run: |
          source /home/kikin/sites/SIGDC/env/bin/activate
          pip install --upgrade pip
          pip install -r /home/kikin/sites/SIGDC/requirements.txt

      - name: Migraciones
        run: |
          source /home/kikin/sites/SIGDC/env/bin/activate
          python /home/kikin/sites/SIGDC/manage.py migrate --noinput

      - name: Archivos estáticos
        run: |
          source /home/kikin/sites/SIGDC/env/bin/activate
          python /home/kikin/sites/SIGDC/manage.py collectstatic --noinput

      - name: Reiniciar servicios
        run: |
          sudo systemctl restart gunicorn_sigdc
          sudo systemctl restart nginx
